version: '3'

services:
  app:
    # ecs-cliでbuildはサポート対象外なため無視される
    build:
      # buildでenvironmentを参照できないのでargsを使う
      args:
        - APP_NAME=$APP_NAME
        - BUILD_CONTEXT=production
      context: .
      dockerfile: ./docker/Dockerfile
    image: tiwvstiw/${APP_NAME}:${BUILD_CONTEXT}-${IMAGE_VERSION}
    environment:
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - public:/${APP_NAME}/public
      - sockets:/${APP_NAME}/tmp/sockets
      - bundle:/usr/local/bundle
      - yarn_cache:/usr/local/share/.cache/yarn/v2
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: $APP_NAME
        awslogs-stream-prefix: $APP_NAME
    command: /bin/sh -c "./entrypoint.sh"

volumes:
  public:
  sockets:
  bundle:
  yarn_cache:
