version: '3'

services:
  app:
    build:
      args:
        - BUILD_CONTEXT=$BUILD_CONTEXT
    environment:
      - RAILS_LOG_TO_STDOUT=
      - SPROCKETS_CACHE=/sprockets_cache
    volumes:
      - .:/${APP_NAME}
      - node_modules:/${APP_NAME}/node_modules
      - sprockets_cache:/sprockets_cache
    logging:
      driver: json-file
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: $APP_NAME
      POSTGRES_PASSWORD: $APP_NAME
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  node_modules:
  sprockets_cache:
  db_data:
