version: '3'

services:
  web:
    image: tiwvstiw${APP_ROOT}_web:$BUILD_CONTEXT
    ports:
      - "80:80"
    logging:
      driver: json-file

  app:
    build:
      args:
        - APP_ROOT=$APP_ROOT
        - BUILD_CONTEXT=$BUILD_CONTEXT
    image: tiwvstiw${APP_ROOT}_app:$BUILD_CONTEXT
    environment:
      - RAILS_LOG_TO_STDOUT=
      - SPROCKETS_CACHE=/sprockets_cache
    volumes:
      - .:/myapp
      - sprockets_cache:/sprockets_cache
    logging:
      driver: json-file
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: myapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sprockets_cache:
  db_data:
